version: "3"
services:
  postgres:
    image: postgres:14.2-bullseye
    networks:
      - grace
    tty: true
    stdin_open: true
    environment:
      POSTGRES_PASSWORD: root      
  mysql:
    image: mysql:8.0
    networks:
      - grace
    tty: true
    stdin_open: true
    environment:
      MYSQL_ROOT_PASSWORD: root        
  development:
    build:
      context: .
    depends_on:
      - postgres
      - mysql
    networks:
      - grace
    tty: true
    stdin_open: true      
      

networks:
  grace:
    driver: bridge